using AutoFixture;
using AutoFixture.AutoMoq;
using AutoFixture.Xunit2;
using CoreLogic;
using FluentAssertions;
using Moq;
using Xunit;

namespace CoreLogic.Tests;

public class UserServiceTests
{
    private readonly Mock<IUserRepository> _mockRepo;
    private readonly UserService _service;

    public UserServiceTests()
    {
        _mockRepo = new Mock<IUserRepository>();
        _service = new UserService(_mockRepo.Object);
    }

    public class InlineAutoMoqDataAttribute : InlineAutoDataAttribute
    {
        public InlineAutoMoqDataAttribute(params object[] objects)
            : base(new AutoMoqDataAttribute(), objects)
        {
        }
    }

    [Fact]
    public void GetUserFullInfo_ExistingUser_ReturnsFormattedString()
    {
        // Arrange
        var user = new User { Id = 42, Name = "Alice", Age = 30 };
        _mockRepo.Setup(r => r.GetUserById(42))
                 .Returns(user);

        // Act
        var result = _service.GetUserFullInfo(42);

        // Assert
        result.Should().Be("Alice is 30 years old.");
        _mockRepo.Verify(r => r.GetUserById(42), Times.Once());
    }

    [Fact]
    public void GetUserFullInfo_NonExistingUser_ReturnsNotFoundMessage()
    {
        // Arrange
        _mockRepo.Setup(r => r.GetUserById(It.IsAny<int>()))
                 .Returns((User?)null);

        // Act
        var result = _service.GetUserFullInfo(999);

        // Assert
        result.Should().Be("User not found");
        _mockRepo.Verify(r => r.GetUserById(999), Times.Once());
    }

    [Fact]
    public void RegisterNewUser_ValidData_CallsSaveAndReturnsTrue()
    {
        // Arrange
        _mockRepo.Setup(r => r.SaveUser(It.IsAny<User>()))
                 .Returns(true);

        // Act
        var success = _service.RegisterNewUser("Bob", 25);

        // Assert
        success.Should().BeTrue();
        _mockRepo.Verify(r => r.SaveUser(It.Is<User>(u =>
            u.Name == "Bob" && u.Age == 25)), Times.Once());
    }

    [Fact]
    public void RegisterNewUser_UnderAge_ReturnsFalse_WithoutCallingRepo()
    {
        // Act
        var success = _service.RegisterNewUser("Charlie", 16);

        // Assert
        success.Should().BeFalse();
        _mockRepo.Verify(r => r.SaveUser(It.IsAny<User>()), Times.Never());
    }

    [Fact]
    public void GetUserFullInfo_RepoThrowsException_PropagatesToCaller()
    {
        // Arrange
        _mockRepo.Setup(r => r.GetUserById(It.IsAny<int>()))
                 .Throws(new InvalidOperationException("Database unavailable"));

        // Act
        Action act = () => _service.GetUserFullInfo(1);

        // Assert
        act.Should().Throw<InvalidOperationException>()
           .WithMessage("Database unavailable");
    }

    [Fact]
    public void RegisterNewUser_WithCallback_TracksSavedUser()
    {
        // Arrange
        User? savedUser = null;

        _mockRepo.Setup(r => r.SaveUser(It.IsAny<User>()))
                 .Callback<User>(u => savedUser = u)
                 .Returns(true);

        // Act
        _service.RegisterNewUser("David", 40);

        // Assert
        savedUser.Should().NotBeNull();
        savedUser!.Name.Should().Be("David");
        savedUser.Age.Should().Be(40);
    }

    [Fact]
    public void Create_User_GeneratesValidInstance()
    {
        var fixture = new Fixture();
        // All integers will be between 1 and 200
        fixture.Customizations.Add(new Int32SequenceGenerator());

        // OR more specific:
        fixture.Customize<User>(c => c.With(u => u.Age, new Random().Next(0, 201)));

        var user = fixture.Create<User>();

        user.Age.Should().BeInRange(0, 200);
    }

    [Fact]
    public void Customize_User_AgeRangeAndNamePrefix()
    {
        var fixture = new Fixture();
        var rnd = new Random();

        fixture.Customize<User>(composer => composer
            // 1. Set age: use a random number without involving fixture.Build
            .With(u => u.Age, () => rnd.Next(18, 78))

            // 2. Set name: use a lambda to generate a dynamic value
            // If you remove the parentheses () => here, the name will be fixed for all tests
            .With(u => u.Name, () => "TestUser_" + Guid.NewGuid().ToString().Substring(0, 5))
        );

        var user = fixture.Create<User>();

        // Assertions
        user.Age.Should().BeInRange(18, 77);
        user.Name.Should().StartWith("TestUser_"); // This will now pass

        // Ensure that Id is still populated by AutoFixture
        user.Id.Should().NotBe(0);
    }


    [Fact]
    public void Build_User_WithoutId()
    {
        var fixture = new Fixture();

        var user = fixture
            .Build<User>()
            .Without(u => u.Id)       
            .With(u => u.Age, 42)
            .Create();

        user.Id.Should().Be(0);
        user.Age.Should().Be(42);
    }

    [Theory]
    [AutoData]
    public void RegisterNewUser_AutoGeneratedValidData_ReturnsTrue(
    string name,
    int age)
    {
        // Arrange
        var mockRepo = new Mock<IUserRepository>();
        mockRepo.Setup(r => r.SaveUser(It.IsAny<User>())).Returns(true);

        var service = new UserService(mockRepo.Object);

        // Act
        var success = service.RegisterNewUser(name, age + 18);

        // Assert
        success.Should().BeTrue();
    }

    [Theory]
    [InlineAutoMoqData("Alice", 25)]
    [InlineAutoMoqData("", 30)]
    public void RegisterNewUser_VariousCases(
        string name,
        int age,
        [Frozen] Mock<IUserRepository> mockRepo,
        UserService service)
    {
        mockRepo.Setup(r => r.SaveUser(It.IsAny<User>())).Returns(true);

        var success = service.RegisterNewUser(name, age);

        if (string.IsNullOrWhiteSpace(name) || age < 18)
            success.Should().BeFalse();
        else
            success.Should().BeTrue();
    }

    public class AutoMoqDataAttribute : AutoDataAttribute
    {
        public AutoMoqDataAttribute() : base(
            () => new Fixture().Customize(new AutoMoqCustomization()))
        {
        }
    }

    [Theory]
    [AutoMoqData]
    public void GetUserFullInfo_AutoMockedRepo_ReturnsFormatted(
    [Frozen] Mock<IUserRepository> mockRepo,
    UserService service,
    User user)   // ← auto-generated
    {
        mockRepo.Setup(r => r.GetUserById(user.Id)).Returns(user);

        var result = service.GetUserFullInfo(user.Id);

        result.Should().Contain(user.Name);
        result.Should().Contain(user.Age.ToString());
    }
}